apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../workflows
- regcred.yaml
patches:
- path: ingress_patch.json
  target:
    group: networking.k8s.io
    kind: Ingress
    name: argo-server
    version: v1
