apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAbugWQQypFzXTyOs+AxpziR3JeKbgWyBuGlnBriBf0pJif5k1FT+e1E+D+wOnqGt0ZCVq3Iyr/Xs10KTGH4UUMd4L7+tJ+i0q5TAeJjIyoA9iFiapOlUnif5sjHrPvgyK9x97DvHqMH466NAfU42Y61VePQyyqVjDicUZRAVwWyb/8w1xuw6KC3G9U6hiyvB5OZX8BlBCI7WcHAiZXWAqybF5YqqSPNfKIEnT3ySBFXpmXYDLY/VwvfqdiMIxXj85FVAZdRm7zowxSchOlFrVWfn1gkc34mGNQF7oLLTg/YaRaLnmbx3W6NQVyy6OGrLVnEToUzw9lGxU9rqrODcqTOn0xmD4YKztdQOlajncsk+hdqEFq1lN3GUos5ZGUlVlpmRO8S5mmwv0EXBTyQ5WvsHig94Etmc+MOy2Dmr1uTFpgXSjCTNp503RU1ylhLdNj2Lda3McpgquZPgi2Rluhf9QBiP5tkGPjxx1vJC8iHtPIPJx6tQ9GTOvrZbq6ALC8V637+XuAiDEX9R1cV8T8St5ddoPp7o0rPrYW55HjbGpgbzf1ysxIMYhS1zT5CwHzYtiXnipW5pmicUfPX78UrDyUYuLTCVExaUISlxHqXRgpsdFeaAhj4gRQt2aS6FwDzk7PBp4tHgFdw3JRskTPcscPSxkoR94WWHIWoUemzFl3bOV2/ZbW0yS0qQEOi/G7AvgqTTLd2JTuyl4nvfLTNHokGnNVEYMpBF67DWnJXEjRpXxGCHwYrjg+jCbD21RZyp4fuAozV2OAYaABQRVY8BKllSVPSZPSF1QsFLGT3EzgWwDuOw2ezUbsb8o6DKSWtDYnotfaTx5oY+jizMFNwmVZiMFVO3zoxg/+K4vljHsqRkgD6qlx0wC8Aep/tixgnmmbAdg/S+WSlA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

