apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-combined-app-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    path: kustomize/overlays/staging
    repoURL: https://github.com/vfarcic/argo-combined-app
    targetRevision: HEAD
    kustomize:
      images:
      - vfarcic/argo-combined-app:79bca4920329b106238c5e1504af51edc85f5c87
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
