apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBSPUoCscks4jzrW1GotjIon/WUQs/znNeBg7jGn2IZ4y02xkvXwueEELy/wvZnyPTkkvlgT0Y4L1zcl2MXv7sM33PQU8AFKPvbsb9GVJ8bT+mAIgpDp4xpaP7pu0p1oOqnvTKuLz/AzdbaOX1fcFUDuWm2eq/Hv/rqsS9/gd/OAy4YJkkEo40GBN9BFj/LDDpg4t4zA9vyZhXGrna8O63ZLEs/8ig6ZJqiVNKp1+Z9H4QI5LMzsEnYTqtt/U20K9D12+6jypWKRxxBYaRZJwR6nVbrGrVlw5ygOepAF7/kzbt5j3Ri9fuLI1JnPgVR1sR1hMeAF1GjEIUMZs9tK6wU0ET3xnBwGHxqAI4a7UOrhRKmjGN4nIrRZazhL7Srv2fLLLE+6dhjwpRefZPjROLBeYtC2jfZfrwxovvRiKt+UjgCpnsW+4k4q0UJD0ETFazgjdvm49N8z8+ycbg60sdMTh6LxmfutWGnb0MKlNZWaWBTkcofoGwC21JHn9dCV7QHEtZr68afzYmpJU7VdMKfJpnBihYuNrSUv/lIlx+MSBnuHuWS3qHnOxhIWExg6ieWcUWxxu4Gcna/HJjOyNoO+Wlu6OEVHu5w5rGSiL7zQQWwtwMIM+Ov+ckhsu3oiLmFV5hkQdo4596d46Pm72I7yGFHsXHpNVhWOfw2bYsljNSE9O5IM+sfXRD4xMlNh0Af5pcKDPkZC3+RGQx8UsMXNOqLaIMyvBZ/AMJeR3AERBzLbOxdSqoZ
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

