apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCNCUj/4VEqACxOYFVWN6Tj3Ju0cUqB8+Pqvv2/cCStlERXZ0uTNuTBUCjHZBQxaMiowRrOOqNia5B+/0/DliH7PI5fpETOHzk+UPUn8v+BCa/KylRKm/b/Mxq4PQfsCEQ5HQ/8myoOp/Y+QTHeveEkH9feCXLUIbTZ60xuvU4CAxEey/lRQZn/4oBbNf7MQ73piuyqFZYp/aK6wXp2nn2UAPK8XXc5ziVOMPHt3raOyKhLGKLcMCHI3xE6qfC+Tx+6cjXg9R9h+k253PCOdon0S2Vb1LdToZHspSHxWm9JnkmEBEOZlI/mazinJQps2yG8BsXmJbusbYlMmr6DQ6G4c+Zun43KqGhXK54ozN+oKdGmZAackLLXZBQd5ZDPy/g2o9daapfwvFnA39M5dABurizH++nHDrXElP0iH2vwrDMs0ikHRl3+qS2tPk6/tkszsIO9+4xKdoUWQmI4KvUuBuLVAQl+1jcMYE2leWxfaDq6gQVZdCJREtJvZii831vqTOzfTtDW+x9h92izC+bbV7zRLw5mFXiObyneI/g3JzJWtrgDP++M5f3kJGwefRcHzbLMVyjkqZq5QRhPrryFZ9srohZPiSdX53xHYNEdCLjYP4jIzc3v35K77pqMMjLH57ekXTk7r4oSaAf26DvTic6zHMbDXNEi3WP3+9I77hYTecbzrroqcr9i6KR1pQyI7ySrI5/jW+Camno5Ufc8xj1m2De/nqiTnWS9tRtrsFGFUhhACYZA
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

