apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCD8Xia0tf7tU4Z8qTX4wn/dolMnANnmsDDVVG0aJuGxwW/G/jKbP82YoZMIVFRdBUZ+zKWErY8jvtmek+9m/FkOteBzo7PO84p0+laDv9u6NI2/yjrlhcUT+bvflXUq0NEy3zhuLreWjPXLE/ds8EooAjoYtr/Nhb+ROmKP2RZeacK3WPfFfCfbJk3hpmoiN0eOrvJQwexIsihZVD5TGlXMbLpMr321/zw1xtcyUDQzgBgsA/uDh/+JU5linW+e9BaoywEi3h9AxAp4flRCZzAp1J1wU7ML1N34BeUSCJYPRwZjvj/AkqafRAQXX22rnLDFLqKTYS9Mp+59h1xslEp3oAkEGDfxXXk7b+42K04BAHs1fTUqUbi9hchLAfXZsOWT0SPucUTfKhPQ7CefqGbwMA3qyYvdICdcYuRDXSVVFPaCOzeSHHrejUgsTrLgApUugaAI5bhFc+8M3Eg8rBrsbRmBbHbQHctI2E/BQ1acGSJGv02J89v90hl5ZcfbgBMCYeSZ9bI/ZfuPFdaAC0d+GfVr+GPVhpXyBNlw8Ox2SiuMoSFrzjqouBC/KmqE/1GjE8BZPyLevh8bp+SEdqSVHW1BQHr9J8dKMkw1Souykiz6k7MK3iCuunwZ/AH7a8e0JpDKShZAsQ99zTf2LF/lL/pFScNj9io0LZYEXu6CyM0Kw0pF/qHoZ39T+jajYJgVoLbl/bxRmxVvmr0XcdYUZu1aU35sgLNnWzpzrse2BW9SjutmtFH
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

