apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBctEDdSAqjSCL0sJqtRGqgd0K+BLEe3w36xUK8yB7P0Mo8RK8twwquMzBDr/pkjSollrefyyjiltfYr3iUMATQQukMbQ0b9e9dQ5RWIASA9THltxPytmrvpBaTaSmpmGfeVFa8CMRvBdIyNnp64tPlb0Ah4iwSSMmQBCHGC/Kj6XkVeTiiUXTMU6RFuLdQgHO/z1EBI8ZilEuqXeRlxTOa2iT2VoRGP1jOcbZ4mu5eEXV4wEdiBLNVkxslZXbzd/PVKuFi0Im9pSDYjU1+EuxGcSW52HTx5ADs1K+y+RfY7PGHzrfS9u60reviwD3u+fMauS+ty/O8pdhDDjwbSz+SYhHf5DHgxKUXsKMcsUhjjFKAw8nSTguhqej0ibwbuDbC7Uns4KpDPah+rROKncL7j8B99r+/KbKZr3HIkDJkHgsRLaEzVOU5r9SUkKJvtVkc3MQkzfS1HHUFp0mQcIK3Omn4PSvr212xsNGvrjlN4PaAjvozCMYSgKCxd+0h/vlGZ9/91X4douFWu4aJ9eRv7zMgeF6LIzvIXMrGaiTInU2fqC5AwmuAf3bfKfhNrMMYyCBeDVlRPeA0reWBYGjiZxe/N9usq/5xW01w0nS5cWK+J2KbfAMngU1W+zfWHhVnUH5rc23bRx13OWm+zdnqOQJnq1OFWLKidS3QIcOBaTU7qmggTbYsv7lvP/BUS/Hf+yE/PU3ts2YJE3nhrVeDUxyK1kgJV58V198q2/7XENOWJRr8GEnO
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

