apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBwMB2EvjmKyTFCDGf3Y7gR4SLjt+zQKkxP+K6S7DslP0MBXLVtWCAo8IAKNX4ecf2+6efWxwHC/MlXilXFWvoHBufkFTYiHCMOwgzmSL8mKOxkkMyfQRUkSd9aXHmTnLZ9aku2iHDiyQb1ApznOPxvKlbR4W3QRXto7+m08FZyp2IC22hS50yAc7ktxlMoscKJ837pHH0F2yL6uAQ3DyXu4MfLIt2IVlMHjn/b1/DVvFtwsD30Xrhbxm4Kn0F2c1Gt5VxvIvykO7jg3YXcTafbEMIVnmCDCCd2jR765SdK8uIytBIX3I9MPkMfH82GAiYks4YB8MvaIDPbtxPhD9rz0cNFP7g8WCBPiHyVX3KleepGO4pDqWXJEWPLV3Q3V4SlDc2Le37+ZZlcQI+393H+tiKa5EQgPbz0FnBwjFqDEyIb/gfYX4NlIEo1Zy2uXnGgkmZiQ99zIMY1hOS8pWDmEqADjW63h6l8mhXDwiQJaNU+Wu7w1+HCUFRV8NpQzNjmjPjyQL3mviw2btEkWO7/RJ37i3cjMfab5GbXxlD01/5be2AI0ZA9qAJW3sMlTBjtUpBKfyT7WDqfmt1eXeBIqE/SQsWLJH6Ji/HOSaMiVXbnVO/bz0gi+vsiJq843RZ/lz2RE3L9hWPNxXUnivvwi2micNVjjWrV1vza2lq+ijNeGrg8czQMld2LNPHQ3JQnzn5JsCx1G+JYa4VKGI2/Vtp3SspAAL3Vl7NfqNi3CSyF9PSUnH++
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

