apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- event-sources.yaml
- sensors.yaml
- githubcred.yaml
namespace: argo-events
patches:
- path: ingress_patch.json
  target:
    group: networking.k8s.io
    kind: Ingress
    name: github
    version: v1
