---

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: github
    eventSourceName: github
    eventName: argo-combined-app
  triggers:
  - template:
      name: trigger
      argoWorkflow:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: argo-combined-app-
              namespace: workflows
            spec:
              entrypoint: build
              serviceAccountName: workflow
              volumes:
              - name: regcred
                secret:
                  secretName: regcred
                  items:
                    - key: .dockerconfigjson
                      path: config.json
              - name: github-access
                secret:
                  secretName: github-access
                  items:
                    - key: token
                      path: token
                    - key: user
                      path: user
                    - key: email
                      path: email
              templates:
              - name: build
                dag:
                  tasks:
                  - name: build
                    templateRef:
                      name: container-image
                      template: build-kaniko-git
                      clusterScope: true
                    arguments:
                      parameters:
                      - name: repo_url
                        value: ""
                      - name: repo_ref
                        value: ""
                      - name: repo_commit_id
                        value: ""
                      - name: container_image
                        value: ""
                      - name: container_tag
                        value: ""
                  - name: promote-staging
                    template: promote
                    arguments:
                      parameters:
                      - name: environment
                        value: staging
                      - name: repo_owner
                      # TODO: Replace
                        value: vfarcic
                      - name: repo_name
                        value: argo-combined-demo
                      - name: image_owner
                      # TODO: Replace
                        value: vfarcic
                      - name: image_name
                        value: ""
                      - name: tag
                        value: ""
                    # TODO: Add the dependency
              - name: promote
                inputs:
                  parameters:
                  - name: environment
                  - name: repo_owner
                  - name: repo_name
                  - name: image_owner
                  - name: image_name
                  - name: tag
                script:
                  image: vfarcic/kustomize:3.9.2
                  command: [sh]
                  source: |
                    set -e
                    ls -la /.github/
                    git clone https://$(cat /.github/token)@github.com/{{inputs.parameters.repo_owner}}/{{inputs.parameters.repo_name}}
                    cd {{inputs.parameters.repo_name}}
                    echo "cat {{inputs.parameters.environment}}/{{inputs.parameters.image_name}}.yaml | sed -e \"s@- {{inputs.parameters.image_owner}}/{{inputs.parameters.image_name}}:.*@- {{inputs.parameters.image_owner}}/{{inputs.parameters.image_name}}:{{inputs.parameters.tag}}@g\""
                    cat {{inputs.parameters.environment}}/{{inputs.parameters.image_name}}.yaml | sed -e "s@- {{inputs.parameters.image_owner}}/{{inputs.parameters.image_name}}:.*@- {{inputs.parameters.image_owner}}/{{inputs.parameters.image_name}}:{{inputs.parameters.tag}}@g" | tee {{inputs.parameters.environment}}/{{inputs.parameters.image_name}}.yaml
                    git config user.name "$(cat /.github/user)"
                    git config user.email "$(cat /.github/email)"
                    git add {{inputs.parameters.environment}}/{{inputs.parameters.image_name}}.yaml
                    git commit -m "Upgraded {{inputs.parameters.environment}}/{{inputs.parameters.image_name}}.yaml with the tag {{inputs.parameters.tag}}"
                    git push
                  volumeMounts:
                    - name: github-access
                      mountPath: /.github/
        parameters:
        - src:
            dependencyName: github
            dataKey: body.repository.git_url
          dest: spec.templates.0.dag.tasks.0.arguments.parameters.0.value
        - src:
            dependencyName: github
            dataKey: body.ref
          dest: spec.templates.0.dag.tasks.0.arguments.parameters.1.value
        - src:
            dependencyName: github
            dataKey: body.after
          dest: spec.templates.0.dag.tasks.0.arguments.parameters.2.value
        - src:
            dependencyName: github
            dataKey: body.repository.full_name
          dest: spec.templates.0.dag.tasks.0.arguments.parameters.3.value
        - src:
            dependencyName: github
            dataKey: body.after
          dest: spec.templates.0.dag.tasks.0.arguments.parameters.4.value
        - src:
            dependencyName: github
            dataKey: body.repository.name
          dest: spec.templates.0.dag.tasks.1.arguments.parameters.4.value
        - src:
            dependencyName: github
            dataKey: body.after
          dest: spec.templates.0.dag.tasks.1.arguments.parameters.5.value
