apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: workflows
spec:
  encryptedData:
    email: AgB2s9yBZsV0cQzBomBJRxSVKN4GyHPrQBiX6kiyXYfigxkNkyvkhdQUBImyNEjTa+Zd/FtPw+bsNdyKFYY7tclN+IcYbeW92k55q4WzkLYHqpcmm4FS/QgyTMPCGbvnjiBqG9i2ny4HyUnWYtZo9DhABsG8rs7aNoEn5isFa66H9GxHs9l0kAPaEA+KsteP6KpnC5Q3PWLSbYXtXgOPbqXEBPHvo1uRc6RFk+Q7VYgFjKPEwjPo73V/m5s0CplLjeUcx5rXIPKdwn01H63UcemjQ2QmDw1tz0DoR6boqE2MCFxMPHEaJBqz4QRp5sL1VZzY20dGvcYbxK5yJCte3WlnZAt+r2UsxF2MyG7iF3vK9V/sHqH/THaSyWY1Cme0udD+Rjf0eGEOaOoecVFJLZVu7vduhocf9LE7No7ysI4+3S4pG8dfgC017t4PplJn+5HbgRtWJFmK1igXX8j9AzIN3M9hlXN+XRnK5getGOFnOnguQ52hqhd7Kmm+Cwneecazc7SAXlNVOpIpa4mIJSloEGZ+Fda1RlmuiMsyXbDSU1P5es5IbGXNq0FVFo0mJMCKYkv6Fga7oILfya8CeUaC5ap7eNLyv/dPJnkKrCHKKV2UmjOAjjE88nYiPM2ov1VPw0stCc51S3TsiRUIKAXnIHocLz1Exe3bKcUWtLQIxErJpNfkp3Fi4/RVwEY8LJjn00YFvgVs0WggRkxELU+6QQ==
    token: AgADE/HUjfHwajbi0pvxQWmAJn7tOHqH0MbuZWwXnnooDPps9D0D6y+VoJpeQhuG3UmBhqgMwBtietBX8JqTNwVX0fa0QAwBRLH/ei/d7m4LIua/pnIlpi1ZoMdwSPdfwIWaojyLmAmXAq4oMin8g/VbX3c8F9TM+VzLHVjmR/LsCCGSYU/AX0Z0OJgayN8PQ4P/tnW+FxGXEmxs0JmFGmcsECJjrAdrbBGV9JfBQexB2cjPEwIp+0I8GAlcWA/4laJlbj21SU9qYTaBnb3v/+4mY64BUtPs0CgEBRvdUw6imhbg4jTTWcc0LZ9wG1Defn8i/zTND4EVGIszgXKvJ7oxVwvFUfME922Yrzu9Q5wrIXrWGhODFPOAd4WXJDlPzD//rabTHumIBQ+fPk2e0oO4DlCTNFNL+dsuYdyTU7HCuh3XPwHN5yr5Kz4d/0XRWDynz2iCr3z7JamssGYHNjuoednw3T4ODp5haLgXoraZ284DTRaC0KUJf22Q7zaFCz5jWX4rjeOPWa7arE5VJzo1TLtPlG0uGxmBQWy6vJoBD2xwmTIFxdoNtQGE3YnZioVR3W75jxdh80/UWt8guHWHBkzSpUrwh8dieINWz0hNsd5zyGWoSbOHyHT/WE3sVmdzY2U+5hoP99hhv7brHS9k2y6jYLgMFIWe5rAhoxvFqJuU1HN0x/XFTteUkJNVyaZWUBY89XYdZ4OyS3gcL7yyku9sp8PNNY7wgNx+qRgc51qj8yBnhnIp
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: workflows
    type: Opaque

